@startuml
skinparam classAttributeIconSize 0
abstract class Ticket{
-ticketCode: int

+Ticket()
+getTicketCode() : int
+{abstract}getPrice() :Double
+{abstract} ticketDesc():String

}

class StudentBusTicket{
+{abstract} ticketDesc():String
}

class AdultBusTicket{
+getPrice() :Double
+ticketDesc():String
}

class OAPBusTicket{
+getPrice() :Double
+ticketDesc():String
}

class KidBusTicket{
+getPrice() :Double
+ticketDesc():String
}

class StudentTrainTicket{
+getPrice() :Double
+ticketDesc():String
}

class AdultTrainTicket{
+getPrice() :Double
+ticketDesc():String
}

class OAPTrainTicket{
+getPrice() :Double
+ticketDesc():String
}

class KidTrainTicket{
+getPrice() :Double
+ticketDesc():String
}

class StudentPlaneTicket{
+getPrice() :Double
+ticketDesc():String
}

class AdultPlaneTicket{
+getPrice() :Double
+ticketDesc():String
}

class OAPPlaneTicket{
+getPrice() :Double
+ticketDesc():String
}

class KidPlaneTicket{
+getPrice() :Double
+ticketDesc():String
}

class MonthlyStudentBusTicket{
+getPrice() :Double
+ticketDesc():String
}

class MonthlyAdultBusTicket{
+getPrice() :Double
+ticketDesc():String
}

class MonthlyOAPBusTicket{
+getPrice() :Double
+ticketDesc():String
}

class MonthlyKidBusTicket{
+getPrice() :Double
+ticketDesc():String
}

class MonthlyStudentTrainTicket{
+getPrice() :Double
+ticketDesc():String
}

class MonthlyAdultTrainTicket{
+getPrice() :Double
+ticketDesc():String
}

class MonthlyOAPTrainTicket{
+getPrice() :Double
+ticketDesc():String
}

class MonthlyKidTrainTicket{
+getPrice() :Double
+ticketDesc():String
}


class Customer{
-name:String
-email:String
-mobileNum:String
+Customer(name: String)
}

class Booking{
-transactionID:String
-customer:Customer
-totalPrice:Double
-ticket:Ticket
+Booking(transID: String; cust:Customer;
 price:Double; ticket:Ticket)
}

Booking --> Ticket : has a
Booking --> Customer : purchased by a

OAPBusTicket --|> Ticket
Ticket <|--- OAPPlaneTicket
Ticket <|-- OAPTrainTicket
MonthlyOAPBusTicket --|> Ticket
AdultPlaneTicket ---|> Ticket
Ticket <|--- MonthlyOAPTrainTicket
KidBusTicket --|> Ticket
Ticket <|--- KidPlaneTicket
Ticket <|--- KidTrainTicket
Ticket <|--- MonthlyKidBusTicket
Ticket <|--- MonthlyKidTrainTicket
Ticket <|- StudentBusTicket
Ticket <|- StudentPlaneTicket
Ticket <|- StudentTrainTicket
Ticket <|--- MonthlyStudentBusTicket
Ticket <|--- MonthlyStudentTrainTicket
AdultBusTicket --|> Ticket
Ticket <|--- AdultTrainTicket
Ticket <|--- MonthlyAdultBusTicket
Ticket <|-- MonthlyAdultTrainTicket







@enduml