@startuml
skinparam classAttributeIconSize 0

interface Obstacle {
    +toString(): String

}

class FlyingObstacle{}

class GroundObstacle{
  -final groundObs: GroundObstacleType;
}


Obstacle <|-- FlyingObstacle

Obstacle <|-- GroundObstacle




@enduml