@startuml
skinparam classAttributeIconSize 0

interface Obstacle {
    +toString(): String

}

class FlyingObstacle{
-OBSTACLE: FlyingObstacleType
}

class GroundObstacle{
  -GROUNDOBS: GroundObstacleType
}

Enum FlyingObstacleType <<enumeration>> {
     BIRD
     CLOUD
     BULLET

    +{static} getRandom(): FlyingObstacleType
}

Enum GroundObstacleType <<enumeration>> {
     SPIKE
     FENCE
     HOLE
     BOX

    +{static} getRandom(): GroundObstacleType
}

interface ObstacleFactory {

    +generateObstacle(o: FlyingObstacleType): Obstacle

    +generateRandomObstacle(): Obstacle
}

class NPCFactory {

    -obstacle: Map<FlyingObstacleType, FlyingObstacle>

  }

  class NPCRandomFactory {


  -randomObstacles: Map<GroundObstacleType, GroundObstacle>

    }


FlyingObstacle --> FlyingObstacleType
GroundObstacle --> GroundObstacleType


Obstacle <|-.- FlyingObstacle

Obstacle <|-.- GroundObstacle

ObstacleFactory <|-.- NPCFactory

ObstacleFactory <|-.- NPCRandomFactory

FlyingObstacle <-.- NPCFactory

GroundObstacle <-.- NPCRandomFactory


class BoxGame {
+main(args: String[])
}




@enduml