@startuml
skinparam classAttributeIconSize 0

interface CharacterBehaviourStrategy<<interface >>{

    +void setLocation(int: x; int: y)
    +void draw(g: Graphics2D)

}


class Character {
    -WIDTH: int
    -HEIGHT: int
    -xCoordinate: int
    -yCoordinate: int
    -isMoving: boolean

    +int getX()
    +int getY()
    +boolean doesContain()
    +void setLocation(int: x; int: y)
    +void draw(g: Graphics2D)

}
class BoxEnemy {

    +void draw(g: Graphics2D)
}

class PyramidEnemy {

    +void draw(g: Graphics2D)
}

class SpikeEnemy {

    +void draw(g: Graphics2D)
}

class HoleEnemy {

    +void draw(g: Graphics2D)
}

class Player {
+void draw(g: Graphics2D)
}

class Enemy {
   -side:int

   +void draw(g: Graphics2D)
}


Character <|-- Enemy
Enemy <|-- BoxEnemy
Enemy <|-- HoleEnemy
Enemy <|-- SpikeEnemy
Enemy <|-- PyramidEnemy
Character<|-- Player

CharacterBehaviourStrategy <- Character
CharacterBehaviourStrategy <|-. LocationBehaviour
CharacterBehaviourStrategy <|-. DrawBehaviour




@enduml