@startuml

skinparam classAttributeIconSize 0


note top of WeatherWatcher
The method gets
called when weather changes
public void weatherChanged(){}
end note


enum WeatherType {
SUNNY
    RAINY
    WINDY
    COLD
    MILD
    SNOW
    STORM
}

interface WeatherWatcher {
 +getUpdate(weather: WeatherType): void
}


class WeatherApp{
-current: WeatherType
-observers: List<WeatherWatcher>

+changeWeather():void

}



interface iObservable {
+addObserver(obs: WeatherWatcher):void
+removeObserver(obs: WeatherWatcher):void
+updateObserver():void
}


class Gardener{

}

class Surfer{

}

class Farmer{

}

WeatherType -> WeatherApp
iObservable-> WeatherWatcher
WeatherApp-.-> iObservable
WeatherWatcher <|-.- Surfer
WeatherWatcher<|-.-Gardener
WeatherWatcher<|-.- Farmer


@enduml