@startuml
'https://plantuml.com/class-diagram
 interface Shape {

  void setLocation(x: int, y: int)
  void draw(g: Graphics2D )

 }



abstract class Rectangle {
    -WIDTH: int
    -HEIGHT: int
    -x: int
    -y: int

    +int getX()
    +int getY()
    +boolean contains()
    +Color {abstract} addColour()
    +int {abstract} addAccessory()

}
class Square {
    +side: int
    -moving: boolean
    -x: int
    -y: int

    + int getX()
    + int getY()
    + boolean getMovingObstacle()
    +void setMovingObstacle(moving: boolean)

}

class Player {

    +int addAccessory()
    +Color addColour()

}

class Obstacle {
   -R: int
   -G: int
   -B: int
}

Shape <|-- Rectangle
Shape <|-- Square
Square <|-- Obstacle
Rectangle <|-- Player




@enduml