@startuml
skinparam classAttributeIconSize 0




abstract class Level {

    +{abstract} void initLevel()
    +void initRain()
    +void initSun()
    +void initSnow()
    +void initDark()
    +void initBright()
    +void initCloud()


}

interface Rain {
  +rain()
}

interface Dark {
 +dark()
}

interface Sunny {
 +sunny()
}

interface Cloudy {
 +cloudy()
}

class MountainLevel {
+initLevel()

}


class SkyLevel {
 +initLevel()

}

class ForestLevel{
+initLevel()
}


Level <|--- SkyLevel
Level <|--- ForestLevel
Level <|--- MountainLevel

Cloudy <|-.- SkyLevel
Sunny <|-.- SkyLevel
Dark <|-.- ForestLevel
Cloudy <|-.- MountainLevel
Rain <|-.- ForestLevel
Sunny <|-.- MountainLevel








@enduml